"""Generate the paper's LaTeX result tables from recorded JSON.

Guardrail 6 (tasking/arxiv_paper.md): every number in the paper must be
regenerable and no table may be hand-typed. This script is the regeneration
step -- it reads the consolidated suite summaries already produced by
paper/analysis/consolidate_task1.py, the signed false-positive audits, and the
ablation comparison, plus paper/results/corpus_tiers.json for the guardrail-1
tier column, and writes ready-to-\\input LaTeX fragments to paper/tables/.
Nothing here re-runs an eval or computes a new number; it only formats numbers
that already exist in paper/results/.

⚠️ RUN_TAG IS THE ONLY THING TO EDIT AFTER A RE-RECORD. It was previously
hard-coded as `20260816` in six places, and when the 2026-08-22/23 re-record
superseded that run the tables kept rendering the OLD numbers into
experiments_results.tex -- NV code accuracy read 39/41 against a golden that had
become 46 elements. SUPERSEDED_TAGS below makes that failure loud instead of
silent.

Inputs (all under paper/results/):
    task1_<RUN_TAG>/summary.json                 (AZ, CA, CO, TX)
    task2_<RUN_TAG>/summary.json                 (NV, KY)
    task1_<RUN_TAG>/task1b_fp_audit_SIGNED.json  verified precision, golden four
    task2_<RUN_TAG>/nv_fp_audit_SIGNED.json      verified precision, held-out
    task3_<RUN_TAG>/ablation_comparison.json     depth-map on/off
    task3_stability_<STABILITY_TAG>/stability_analysis.json   (optional)
    corpus_tiers.json

Outputs:
    paper/tables/detector_headline.tex
    paper/tables/parser_headline.tex
    paper/tables/ablation_depthmap.tex

Usage (from repo root):
    python paper/analysis/generate_tables.py
"""

import json
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parent.parent
RESULTS_DIR = PAPER_DIR / "results"
TABLES_DIR = PAPER_DIR / "tables"

# The recorded freeze these tables describe. Edit ONLY this after a re-record.
RUN_TAG = "20260822"
STABILITY_TAG = "20260823"

# Runs that have been superseded. Pointing RUN_TAG at one of these is almost
# always a mistake -- the whole reason this constant exists.
SUPERSEDED_TAGS = {"20260816"}

GOLDEN_STATES = ["AZ", "CA", "CO", "TX"]
HELDOUT_STATES = ["NV", "KY"]
ALL_STATES = GOLDEN_STATES + HELDOUT_STATES

STATE_TIER_KEY = {"AZ": "AZ", "CA": "CA", "CO": "CO", "TX": "TX",
                  "NV": "NV_2023", "KY": "KY"}


def load_json(path):
    with open(path) as f:
        return json.load(f)


def esc(s):
    return str(s).replace("_", r"\_").replace("%", r"\%")


def fmt_pct(x):
    return "--" if x is None else f"{x * 100:.1f}"


def bool_mark(b):
    return "PASS" if b else r"\textbf{FAIL}"


def header(*sources):
    src = ", ".join(sources)
    return [
        "% AUTO-GENERATED by paper/analysis/generate_tables.py -- do not hand-edit.",
        f"% Source: {src}",
        "% Regenerate with: python paper/analysis/generate_tables.py",
        "% Corpus tier (guardrail 1): every row is the _only_subset tier, never full-document.",
    ]


def build_detector_table(det, tiers, verified):
    L = header(f"paper/results/task1_{RUN_TAG}/summary.json",
               f"task2_{RUN_TAG}/summary.json",
               "the signed FP audits, corpus_tiers.json")
    L += [r"\begin{table*}", r"  \centering", r"  \begin{tabular}{lrrrrrrl}", r"    \hline",
          r"    \textbf{State} & \textbf{Role} & \textbf{Subset pp} & \textbf{Recall} & "
          r"\textbf{Verified prec.} & \textbf{Code acc.} & \textbf{Desc. acc.} & "
          r"\textbf{Depth map} \\", r"    \hline"]
    for st in ALL_STATES:
        d = det[st]
        tier = tiers["tiers"][STATE_TIER_KEY[st]]
        dt = d["description_total"]
        desc = fmt_pct(d["description_accuracy"]) + (f" ({d['description_matches']}/{dt})" if dt else "")
        vp = verified.get(st)
        L.append(f"    {st} & {tier['role']} & {tier['only_subset']} & "
                 f"{fmt_pct(d['recall'])} & {fmt_pct(vp)} & "
                 f"{fmt_pct(d['code_accuracy'])} ({d['code_matches']}/{d['code_total']}) & "
                 f"{desc if dt else '--'} & {bool_mark(d['depth_map_passed'])} \\\\")
    L += [r"    \hline", r"  \end{tabular}",
          r"  \caption{Detector recall, verified precision, code and description "
          r"accuracy, and depth-map pass/fail, per state. \textbf{Verified precision} "
          r"is (in-scope detections $-$ hallucinations) / in-scope detections, from the "
          r"manual false-positive audit; every unmatched in-scope detection in all six "
          r"states was audited and signed by the author. Raw suite precision is NOT "
          r"reported: the detector goldens are partial spot-checks, so it measures "
          r"annotation coverage rather than correctness (\S\ref{sec:discussion-limitations}). All "
          r"numbers are on the \emph{\_only\_subset} corpus tier (8--15pp manually "
          r"trimmed subsets; see \S\ref{sec:corpus}), never full documents. "
          rf"Source: \texttt{{paper/results/task1\_{RUN_TAG}/}}, "
          rf"\texttt{{task2\_{RUN_TAG}/}}.}}",
          r"  \label{tab:detector-headline}", r"\end{table*}"]
    return "\n".join(L) + "\n"


def build_parser_table(par, tiers):
    L = header(f"paper/results/task1_{RUN_TAG}/summary.json",
               f"task2_{RUN_TAG}/summary.json", "corpus_tiers.json")
    L += [r"\begin{table*}", r"  \centering", r"  \begin{tabular}{lrrrrrr}", r"    \hline",
          r"    \textbf{State} & \textbf{Role} & \textbf{Coverage} & \textbf{Field acc.} & "
          r"\textbf{Fully correct} & \textbf{Standards} & \textbf{ID collisions} \\",
          r"    \hline"]
    for st in ALL_STATES:
        p = par[st]
        tier = tiers["tiers"][STATE_TIER_KEY[st]]
        L.append(f"    {st} & {tier['role']} & {fmt_pct(p['coverage'])} "
                 f"({p['matched']}/{p['n_golden']}) & {fmt_pct(p['field_accuracy'])} & "
                 f"{p['fully_correct']}/{p['n_golden']} & {p['n_parsed']} & "
                 f"{len(p['id_collisions'])} \\\\")
    L += [r"    \hline", r"  \end{tabular}",
          r"  \caption{Parser coverage, per-field accuracy, fully-correct standards, "
          r"standards emitted, and \texttt{standard\_id} collisions, per state. All "
          r"numbers are on the \emph{\_only\_subset} corpus tier "
          r"(\S\ref{sec:corpus}), never full documents. "
          rf"Source: \texttt{{paper/results/task1\_{RUN_TAG}/}}, "
          rf"\texttt{{task2\_{RUN_TAG}/}}.}}",
          r"  \label{tab:parser-headline}", r"\end{table*}"]
    return "\n".join(L) + "\n"


def build_ablation_table(abl, stab):
    L = header(f"paper/results/task3_{RUN_TAG}/ablation_comparison.json",
               f"task3_stability_{STABILITY_TAG}/stability_analysis.json")
    pooled = abl["aggregate"]["pooled_by_level"]
    L += [r"\begin{table}", r"  \centering", r"  \begin{tabular}{lrr}", r"    \hline",
          r"    \textbf{Level} & \textbf{Recall, depth map on} & "
          r"\textbf{Recall, depth map off} \\", r"    \hline"]
    for lv in ("domain", "strand", "sub_strand", "indicator"):
        v = pooled.get(lv)
        if not v:
            continue
        L.append(f"    {esc(lv)} & {fmt_pct(v['on_recall'])} & {fmt_pct(v['off_recall'])} \\\\")
    L += [r"    \hline", r"  \end{tabular}"]

    degraded = abl["aggregate"]["states_with_recall_drop"]
    unaffected = [s for s in ALL_STATES if s not in degraded]
    cases = ", ".join(rf"\texttt{{{esc(c)}}}"
                      for c in abl["aggregate"]["total_regressions_newly_failing"])
    extra = ""
    if stab:
        ag = stab["aggregate"]
        rng = stab["per_state"]
        parts = []
        for s in ag["states_with_reproducible_degradation"]:
            lo, hi = rng[s]["off"]["recall_range"]
            parts.append(f"{s} {lo * 100:.0f}--{hi * 100:.0f}\\%")
        extra = (r" Repeated runs ($n{=}2$--$3$ per arm per state) reproduce the "
                 r"\emph{direction} in every sample and never flip its sign, but the "
                 r"\emph{magnitude} varies: off-arm recall spans "
                 + ", ".join(parts) + r". No regression case changed status in any run. "
                 r"Point estimates from a single run are therefore not reported.")

    L += [r"  \caption{Depth-map ablation, pooled over all six states. Removing the "
          r"Pass-1 depth map leaves \emph{domain} recall untouched and degrades the "
          r"levels whose identity depends on nesting position. Per state, "
          rf"{', '.join(degraded)} degrade while {', '.join(unaffected)} are unaffected. "
          rf"The categorical evidence is {cases}, which fail with the depth map "
          rf"disabled and pass with it enabled." + extra +
          r" All numbers are on the \emph{\_only\_subset} corpus tier.}",
          r"  \label{tab:ablation-depthmap}", r"\end{table}"]
    return "\n".join(L) + "\n"


def verified_precision_by_state():
    """Read the SIGNED audits. These files exist precisely because regenerating
    the evidence JSON resets `verified_by` to UNSIGNED, so they -- not
    heldout_evidence.json -- are the authority for a published number."""
    out = {}
    g = RESULTS_DIR / f"task1_{RUN_TAG}" / "task1b_fp_audit_SIGNED.json"
    if g.exists():
        out.update(load_json(g)["verified_precision"])
    h = RESULTS_DIR / f"task2_{RUN_TAG}" / "nv_fp_audit_SIGNED.json"
    if h.exists():
        out.update(load_json(h)["verified_precision"])
    missing = [s for s in ALL_STATES if s not in out]
    if missing:
        raise SystemExit(
            f"No SIGNED verified-precision figure for {missing}. The audit must be "
            "signed before its number enters a table -- an unsigned first pass is "
            "not quotable (guardrail 8).")
    return out


def main():
    if RUN_TAG in SUPERSEDED_TAGS:
        raise SystemExit(f"RUN_TAG={RUN_TAG} is a SUPERSEDED run. Point it at the "
                         "current freeze before generating tables.")
    t1 = load_json(RESULTS_DIR / f"task1_{RUN_TAG}" / "summary.json")
    t2 = load_json(RESULTS_DIR / f"task2_{RUN_TAG}" / "summary.json")
    tiers = load_json(RESULTS_DIR / "corpus_tiers.json")
    abl = load_json(RESULTS_DIR / f"task3_{RUN_TAG}" / "ablation_comparison.json")
    sp = RESULTS_DIR / f"task3_stability_{STABILITY_TAG}" / "stability_analysis.json"
    stab = load_json(sp) if sp.exists() else None

    det = {**t1["detector"], **t2["detector"]}
    par = {**t1["parser"], **t2["parser"]}
    missing = [s for s in ALL_STATES if s not in det]
    if missing:
        raise SystemExit(f"missing detector results for: {missing}")

    TABLES_DIR.mkdir(exist_ok=True)
    written = [
        ("detector_headline.tex", build_detector_table(det, tiers, verified_precision_by_state())),
        ("parser_headline.tex", build_parser_table(par, tiers)),
        ("ablation_depthmap.tex", build_ablation_table(abl, stab)),
    ]
    for name, body in written:
        (TABLES_DIR / name).write_text(body)
        print(f"wrote {TABLES_DIR / name}")
    if stab is None:
        print("NOTE: no stability_analysis.json found; ablation caption omits the "
              "repeated-run ranges.")


if __name__ == "__main__":
    main()
