"""Generate the paper's LaTeX result tables from recorded JSON.

Guardrail 6 (tasking/arxiv_paper.md): every number in the paper must be
regenerable and no table may be hand-typed. This script is the regeneration
step — it reads the consolidated suite summaries already produced by
paper/analysis/consolidate_task1.py (golden four) and the equivalent Task 2
consolidation (held-out NV/KY), plus paper/results/corpus_tiers.json for the
guardrail-1 tier column, and writes ready-to-\\input LaTeX table fragments to
paper/tables/. Nothing here re-runs an eval or computes a new number; it only
formats numbers that already exist in paper/results/.

Inputs:
    paper/results/task1_20260816/summary.json   (AZ, CA, CO, TX)
    paper/results/task2_20260816/summary.json   (NV, KY)
    paper/results/corpus_tiers.json

Outputs:
    paper/tables/detector_headline.tex
    paper/tables/parser_headline.tex

Usage (from repo root):
    python paper/analysis/generate_tables.py
"""

import json
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parent.parent
RESULTS_DIR = PAPER_DIR / "results"
TABLES_DIR = PAPER_DIR / "tables"

GOLDEN_STATES = ["AZ", "CA", "CO", "TX"]
HELDOUT_STATES = ["NV", "KY"]

STATE_TIER_KEY = {
    "AZ": "AZ", "CA": "CA", "CO": "CO", "TX": "TX",
    "NV": "NV_2023", "KY": "KY",
}


def load_json(path):
    with open(path) as f:
        return json.load(f)


def esc(s):
    """Escape LaTeX special characters in a plain data string."""
    return str(s).replace("_", r"\_").replace("%", r"\%")


def fmt_pct(x):
    if x is None:
        return "--"
    return f"{x * 100:.1f}"


def bool_mark(b):
    return "PASS" if b else r"\textbf{FAIL}"


def build_detector_table(detector_by_state, tiers):
    lines = []
    lines.append("% AUTO-GENERATED by paper/analysis/generate_tables.py — do not hand-edit.")
    lines.append("% Source: paper/results/task1_20260816/summary.json, task2_20260816/summary.json,")
    lines.append("% corpus_tiers.json. Regenerate with: python paper/analysis/generate_tables.py")
    lines.append("% Corpus tier (guardrail 1): every row is the _only_subset tier, never full-document.")
    lines.append(r"\begin{table*}")
    lines.append(r"  \centering")
    lines.append(r"  \begin{tabular}{lrrrrrl}")
    lines.append(r"    \hline")
    lines.append(
        r"    \textbf{State} & \textbf{Role} & \textbf{Subset pp} & \textbf{Recall} & "
        r"\textbf{Code acc.} & \textbf{Desc. acc.} & \textbf{Depth map} \\"
    )
    lines.append(r"    \hline")
    for state in GOLDEN_STATES + HELDOUT_STATES:
        d = detector_by_state[state]
        tier = tiers["tiers"][STATE_TIER_KEY[state]]
        role = tier["role"]
        pp = tier["only_subset"]
        recall = fmt_pct(d["recall"])
        code_acc = fmt_pct(d["code_accuracy"])
        desc_total = d["description_total"]
        desc_acc = fmt_pct(d["description_accuracy"]) if desc_total else "--"
        depth = bool_mark(d["depth_map_passed"])
        lines.append(
            f"    {state} & {role} & {pp} & {recall} & {code_acc} "
            f"({d['code_matches']}/{d['code_total']}) & {desc_acc}"
            + (f" ({d['description_matches']}/{desc_total})" if desc_total else "")
            + f" & {depth} \\\\"
        )
    lines.append(r"    \hline")
    lines.append(r"  \end{tabular}")
    lines.append(
        r"  \caption{Detector recall, code and description accuracy, and depth-map "
        r"pass/fail, per state. All numbers are on the \emph{\_only\_subset} corpus "
        r"tier (8--15pp manually trimmed subsets; see \S\ref{sec:corpus}), never "
        r"full documents. Golden = AZ/CA/CO/TX; held-out = NV-2023/KY. Source: "
        r"\texttt{paper/results/task1\_20260816/}, \texttt{task2\_20260816/}.}"
    )
    lines.append(r"  \label{tab:detector-headline}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


def build_parser_table(parser_by_state, tiers):
    lines = []
    lines.append("% AUTO-GENERATED by paper/analysis/generate_tables.py — do not hand-edit.")
    lines.append("% Source: paper/results/task1_20260816/summary.json, task2_20260816/summary.json,")
    lines.append("% corpus_tiers.json. Regenerate with: python paper/analysis/generate_tables.py")
    lines.append("% Corpus tier (guardrail 1): every row is the _only_subset tier, never full-document.")
    lines.append(r"\begin{table*}")
    lines.append(r"  \centering")
    lines.append(r"  \begin{tabular}{lrrrrr}")
    lines.append(r"    \hline")
    lines.append(
        r"    \textbf{State} & \textbf{Role} & \textbf{Coverage} & \textbf{Field acc.} & "
        r"\textbf{Standards} & \textbf{ID collisions} \\"
    )
    lines.append(r"    \hline")
    for state in GOLDEN_STATES + HELDOUT_STATES:
        p = parser_by_state[state]
        tier = tiers["tiers"][STATE_TIER_KEY[state]]
        role = tier["role"]
        coverage = fmt_pct(p["coverage"])
        field_acc = fmt_pct(p["field_accuracy"])
        n_parsed = p["n_parsed"]
        n_collisions = len(p["id_collisions"])
        lines.append(
            f"    {state} & {role} & {coverage} ({p['matched']}/{p['n_golden']}) & "
            f"{field_acc} & {n_parsed} & {n_collisions} \\\\"
        )
    lines.append(r"    \hline")
    lines.append(r"  \end{tabular}")
    lines.append(
        r"  \caption{Parser coverage, per-field accuracy, standards emitted, and "
        r"\texttt{standard\_id} collisions, per state. All numbers are on the "
        r"\emph{\_only\_subset} corpus tier (\S\ref{sec:corpus}), never full "
        r"documents. Golden = AZ/CA/CO/TX; held-out = NV-2023/KY. Source: "
        r"\texttt{paper/results/task1\_20260816/}, \texttt{task2\_20260816/}.}"
    )
    lines.append(r"  \label{tab:parser-headline}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


def main():
    task1 = load_json(RESULTS_DIR / "task1_20260816" / "summary.json")
    task2 = load_json(RESULTS_DIR / "task2_20260816" / "summary.json")
    tiers = load_json(RESULTS_DIR / "corpus_tiers.json")

    detector_by_state = {**task1["detector"], **task2["detector"]}
    parser_by_state = {**task1["parser"], **task2["parser"]}

    missing = [s for s in GOLDEN_STATES + HELDOUT_STATES if s not in detector_by_state]
    if missing:
        raise SystemExit(f"missing detector results for: {missing}")

    TABLES_DIR.mkdir(exist_ok=True)
    (TABLES_DIR / "detector_headline.tex").write_text(
        build_detector_table(detector_by_state, tiers)
    )
    (TABLES_DIR / "parser_headline.tex").write_text(
        build_parser_table(parser_by_state, tiers)
    )
    print(f"wrote {TABLES_DIR / 'detector_headline.tex'}")
    print(f"wrote {TABLES_DIR / 'parser_headline.tex'}")


if __name__ == "__main__":
    main()
