"""Generate Appendix A (prompts) from the LIVE prompt builders.

Guardrail 6, applied to prose rather than numbers: the appendix is the paper's
substitute for releasing the code, so a prompt that has drifted from the
implementation would be a false disclosure. Rendering it from
``detector.build_depth_map_prompt`` / ``build_detection_prompt`` and
``parser.build_parsing_prompt`` makes drift impossible -- rerun this and the
appendix follows the source.

The document content each prompt appends is replaced by a placeholder; that is
per-run input, not part of the instruction, and reproducing one chunk of a
third-party PDF here would be a redistribution we cannot grant.

Run: python paper/analysis/make_prompt_appendix.py
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "src"))

from els_pipeline.detector import build_depth_map_prompt, build_detection_prompt  # noqa: E402
from els_pipeline.parser import build_parsing_prompt  # noqa: E402

OUT = ROOT / "paper" / "tables" / "appendix_prompts.tex"

DEPTH_MAP_EXAMPLE = {
    "doc_depths": [
        {"depth": 1, "canonical_level": "domain", "label_in_doc": "Domain",
         "prefix_pattern": "ALL-CAPS HEADING", "example": "APPROACHES TO LEARNING"},
        {"depth": 2, "canonical_level": "strand", "label_in_doc": "Standard",
         "prefix_pattern": "<Area> Standard N", "example": "Approaches to Learning Standard 1"},
    ],
    "notes": "",
}


def rendered():
    """Render each prompt from the live builder, then blank the per-run input."""
    depth = build_depth_map_prompt([])
    detect = build_detection_prompt([], depth_map=DEPTH_MAP_EXAMPLE)
    parse = build_parsing_prompt([], "US", "KY", 2021, "36-60")

    def strip_doc(text, marker):
        i = text.find(marker)
        return (text if i < 0 else text[:i] + marker
                + "\n\n<<serialized document lines, one per row, each prefixed\n"
                  "  [Page N | x=<left edge as fraction of page width>]>>\n")

    depth = strip_doc(depth, "DOCUMENT SAMPLE:")
    detect = strip_doc(detect, "DOCUMENT CHUNK:")
    parse = re.sub(r"(DETECTED ELEMENTS[^\n]*\n)(.*)$", r"\1\n<<serialized detected elements>>\n",
                   parse, flags=re.S)
    return depth, detect, parse


def block(title, label, body):
    return "\n".join([
        rf"\subsection{{{title}}}", rf"\label{{{label}}}",
        r"\begin{lstlisting}[style=promptstyle]",
        body.rstrip(), r"\end{lstlisting}", "",
    ])


def main():
    depth, detect, parse = rendered()
    parts = [
        "% AUTO-GENERATED by paper/analysis/make_prompt_appendix.py -- do not hand-edit.",
        "% Rendered from the live prompt builders so the appendix cannot drift from the",
        "% implementation it discloses. Regenerate with:",
        "%   python paper/analysis/make_prompt_appendix.py",
        "",
        r"The three prompts below are reproduced as the system emits them, with only the",
        r"per-run document content replaced by a placeholder. Together with the schema of",
        r"Appendix~\ref{sec:appendix-schema} they are what this paper discloses in place of",
        r"a code release (\S\ref{sec:artifacts-statement}).",
        "",
        block("Pass 1: depth-map inference", "sec:prompt-depthmap", depth),
        block("Pass 2: per-chunk detection", "sec:prompt-detection", detect),
        block("Parsing", "sec:prompt-parsing", parse),
    ]
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")
    for name, body in (("depth map", depth), ("detection", detect), ("parsing", parse)):
        print(f"  {name}: {len(body):,} chars, {body.count(chr(10))} lines")


if __name__ == "__main__":
    main()
