"""Generate Appendix C (representative golden examples) from the golden files.

Each example is chosen to illustrate ONE convention the body of the paper
argues about, and every field is copied from the annotation on disk rather than
retyped, so the appendix cannot drift from what was actually graded.

Long free-text descriptions are truncated for display and marked; the code,
level and identifier fields -- the parts the conventions turn on -- are never
truncated.

Run: python paper/analysis/make_goldens_appendix.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
GOLD_D = ROOT / "evaluation" / "ground_truth_detector"
GOLD_P = ROOT / "evaluation" / "ground_truth_parser"
OUT = ROOT / "paper" / "tables" / "appendix_goldens.tex"

DESC_CAP = 110


def esc(x):
    if x is None:
        return r"\textit{null}"
    s = str(x)
    if len(s) > DESC_CAP:
        s = s[:DESC_CAP].rstrip() + " [...]"
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}"), ("—", "---"), ("’", "'"), ("“", "``"), ("”", "''")]:
        s = s.replace(a, b)
    return s


def tt(x):
    """A breakable \\texttt: identifiers like US-CA-2021-AL.1.0.INIT.1.2.36-54 have
    no break points inside \\texttt, so in a narrow two-column table they overflow
    the column rather than wrapping. Allow a break after each dot and hyphen."""
    if x is None:
        return r"\textit{null}"
    s = esc(x)
    for ch in (".", "-", "\\_"):
        s = s.replace(ch, ch + r"\allowbreak{}")
    return r"\texttt{" + s + "}"


def det(state, tid):
    d = json.loads((GOLD_D / f"{state}.json").read_text())
    els = d.get("elements", d)
    return next(e for e in els if e["test_case_id"] == tid)


def par(state, tid):
    d = json.loads((GOLD_P / f"{state}.json").read_text())
    return next(s for s in d["standards"] if s["test_case_id"] == tid)["expected"]


def detector_block(state, tid, caption):
    e = det(state, tid)
    rows = [rf"\texttt{{level}} & {tt(e['level'])} \\",
            rf"\texttt{{code}} & {tt(e['code'])} \\",
            rf"\texttt{{title}} & {esc(e['title'])} \\",
            rf"\texttt{{description}} & {esc(e.get('description'))} \\",
            rf"\texttt{{source\_page}} & {e['source_page']} \\"]
    return "\n".join([
        rf"\paragraph{{{state} \textnormal{{---}} {caption}}}",
        rf"\noindent\scriptsize\begin{{tabular}}{{@{{}}p{{0.22\linewidth}}p{{0.72\linewidth}}@{{}}}}",
        r"\toprule", *rows, r"\bottomrule", r"\end{tabular}", "",
        rf"\noindent{{\scriptsize\raggedright Golden entry \texttt{{{esc(tid)}}}, "
        rf"\texttt{{evaluation/ground\_truth\_detector/{state}.json}}.\par}}", "",
    ])


def parser_block(state, tid, caption):
    x = par(state, tid)
    rows = [rf"\texttt{{standard\_id}} & {tt(x['standard_id'])} \\"]
    for lvl in ("domain", "strand", "sub_strand", "indicator"):
        v = x.get(lvl)
        if v is None:
            rows.append(rf"\texttt{{{esc(lvl)}}} & \textit{{absent --- this document has no "
                        rf"such level}} \\")
        else:
            rows.append(rf"\texttt{{{esc(lvl)}.code}} & {tt(v['code'])} \\")
            rows.append(rf"\texttt{{{esc(lvl)}.name}} & {esc(v['name'])} \\")
    rows.append(rf"\texttt{{age\_band}} & {esc(x.get('age_band'))} \\")
    return "\n".join([
        rf"\paragraph{{{state} \textnormal{{---}} {caption}}}",
        rf"\noindent\scriptsize\begin{{tabular}}{{@{{}}p{{0.26\linewidth}}p{{0.68\linewidth}}@{{}}}}",
        r"\toprule", *rows, r"\bottomrule", r"\end{tabular}", "",
        rf"\noindent{{\scriptsize\raggedright Golden entry \texttt{{{esc(tid)}}}, "
        rf"\texttt{{evaluation/ground\_truth\_parser/{state}.json}}. Descriptions elided.\par}}", "",
    ])


def main():
    parts = [
        "% AUTO-GENERATED by paper/analysis/make_goldens_appendix.py -- do not hand-edit.",
        "% Every field is copied from the annotation on disk, so the appendix cannot drift",
        "% from what was actually graded. Regenerate with:",
        "%   python paper/analysis/make_goldens_appendix.py",
        "",
        r"Both suites are graded against independently annotated golden sets with different "
        r"shapes: the detector golden is a flat list of elements, the parser golden a nested "
        r"record per standard. The examples below were each chosen to show one convention the "
        r"body of the paper turns on. Free-text descriptions are elided for length; codes, "
        r"levels and identifiers are reproduced in full.",
        "",
        detector_block("KY", "KY-SUB-01",
                       r"a \texttt{<Label> <id>} heading, where the label-and-id \emph{is} the code"),
        parser_block("KY", "KY-STD-01",
                     r"the same element after parsing, its label form resolved to a "
                     r"domain-qualified code"),
        parser_block("NV", "NV-STD-01",
                     r"a printed namespace that skips a level: the sub-strand code does "
                     r"\emph{not} extend the strand's"),
        parser_block("CO", "CO-IND-01",
                     r"a three-level document --- \texttt{sub\_strand} is absent by design, "
                     r"not missing"),
        parser_block("CA", "CA-IND-01-EARLY",
                     r"a side-by-side column variant, disambiguated inside the indicator code"),
    ]
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
